apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: game-2048-devops
  app.kubernetes.io/managed-by: kustomize

namespace: game-2048

images:
  - name: ghcr.io/yugandhar99/2048-game-devops
    newTag: latest
